apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: registry-vpc.cn-shenzhen.aliyuncs.com/kuaifu-test/xmkf-data-center-web:2025-06-24-11-45-17_37_b300dce6e45d66cc27f9d341bdcbd91b8815e22c
          name: guestbook-ui
          ports:
            - containerPort: 80
